#ifndef VIDEOINTERFACEDBUS_GLOBAL_H
#define VIDEOINTERFACEDBUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIDEOINTERFACEDBUS_LIBRARY)
#define VIDEOINTERFACEDBUS_EXPORT Q_DECL_EXPORT
#else
#define VIDEOINTERFACEDBUS_EXPORT Q_DECL_IMPORT
#endif

#endif // VIDEOINTERFACEDBUS_GLOBAL_H
